version: "3.8"


services:
  driver:
    image: spark-node:1.0.1
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=driver
      - SPARK_WORKLOAD=master
    restart: unless-stopped
    
  worker-1:
    image: spark-node:1.0.1
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - driver
    environment:
      - SPARK_MASTER=spark://driver:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=worker-1
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    restart: unless-stopped

  worker-2:
    image: spark-node:1.0.1
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - driver
    environment:
      - SPARK_MASTER=spark://driver:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=3G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=worker-2
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    restart: unless-stopped
